import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  defaultSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction to ARP',
    },
    {
      type: 'doc',
      id: 'quickstart',
      label: 'Getting Started',
    },
    {
      type: "category",
      label: "User Guides",
      link: {type: 'doc', id: 'guides/index'},
      items: [
        {
          type: "autogenerated",
          dirName: "guides",
        }
      ]
    },
    {
      type: "category",
      label: "ARP Standard",
      link: {type: 'doc', id: 'arp-standard/index'},
      items: [
        {
          type: "autogenerated",
          dirName: "arp-standard",
        }
      ]
    },
    {
      type: "category",
      label: "JARVIS Implementation",
      link: {type: 'doc', id: 'jarvis/index'},
      items: [
        {
          type: "autogenerated",
          dirName: "jarvis",
        }
      ]
    },
    {
      type: "category",
      label: "Integrations",
      link: {type: 'doc', id: 'integrations/index'},
      items: [
        {
          type: "autogenerated",
          dirName: "integrations",
        }
      ]
    },
    {
      type: "category",
      label: "API Reference",
      link: {type: 'doc', id: 'api-reference/index'},
      items: [
        {
          type: "autogenerated",
          dirName: "api-reference",
        }
      ]
    },
    {
      type: "category",
      label: "Resources",
      link: {type: 'doc', id: 'resources/index'},
      collapsible: false,
      items: [
        {
          type: "autogenerated",
          dirName: "resources",
        }
      ]
    }
  ]  
};

export default sidebars;
